### ISSUE TITLE
[Cygwin] Arduino port COM3 not found!

### ISSUE THREAD

**Issue by msebek** [sudar/Arduino-Makefile#294]
I'm working on a project team where members are using Windows, Mac and Linux. People using Mac and Linux are successfully using the Makefile, but people using Windows cannot. 

I am able to `MONITOR_PORT="/dev/ttyS3" make reset`, (though it required me to upload a program through the arduino IDE before I was able to), but `MONITOR_PORT="/dev/ttyS3" make upload` failed.

The full output from running this command can be found here: http://pastebin.com/P0H7jgM7
The gist of it is summarized below:

```
$ MONITOR_PORT="/dev/ttyS2" make upload
...
- [COMPUTED]           DEVICE_PATH = /dev/ttyS2 (from MONITOR_PORT)
...
make do_upload
make[1]: Entering directory '/cygdrive/c/Users/Matt/OneDrive/workspace/RoboBuggy-2015/arduino_src/RadioBuggyMega'
../../../../../../../arduino/hardware/tools/avr/bin/avrdude -V -v -v -p atmega2560 -C ../../../../../../../arduino/hardware/tools/avr/etc/avrdude.conf -c wiring -b 115200 -P com/dev/ttyS2 \
                -U flash:w:build-mega2560/RadioBuggyMega.hex:i

avrdude.exe: Version 5.11, compiled on Sep  2 2011 at 19:38:36
             Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
             Copyright (c) 2007-2009 Joerg Wunsch

             System wide configuration file is "../../../../../../../arduino/hardware/tools/avr/etc/avrdude.conf"

             Using Port                    : com/dev/ttyS2
             Using Programmer              : wiring
             Overriding Baud Rate          : 115200
avrdude.exe: ser_open(): can't open device "\\.\com/dev/ttyS2": The system cannot find the path specified.
```

When I try to 'MONITOR_PORT="COM3" make reset', I get the following error. ```

```
    Resetting Arduino...
    ../Arduino.mk:1300: *** Arduino port COM3 not found!.  Stop.
```

**Repro**
**_Installation**_
1. Install cygwin with make and python installed from cygwin repos. 
2. Install pip per instructions on pip website. 

> wget https://bootstrap.pypa.io/get-pip.py
> /user/bin/env python get-pip.py
> 3. Install pyserial
> pip install pyserial
> 4. make reset/make upload
> Also of note:
> 
> ```
> Matt@icarus /cygdrive/c/Users/Matt/OneDrive/workspace/RoboBuggy-2015/arduino_src/RadioBuggyMega
> $ python
> Python 2.7.8 (default, Jul 28 2014, 01:34:03)
> [GCC 4.8.3] on cygwin
> Type "help", "copyright", "credits" or "license" for more information.
> >> import serial
> >> s = serial.Serial("COM3")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/site-packages/serial/serialutil.py", line 282, in __init__
>     self.open()
>   File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 289, in open
>     self.fd = os.open(self.portstr, os.O_RDWR|os.O_NOCTTY|os.O_NONBLOCK)
> OSError: [Errno 2] No such file or directory: 'COM3'
> >> s = serial.Serial("/dev/ttyS2")
> (successful)
> ```

Any thoughts/reports on how to make uploading on windows work? If you need any more information, I can provide it. Thanks!

**Comment by jhyslop** [comment]
Hi,

I ran into this problem as well. I'm running Windows 10 with Cygwin. The versions reported by Arduino.mk are: ARDMK_VERSION = 1.6, CC_VERSION = 7.3.0 (avr-gcc), ARDUINO_VERSION = 1813

I discovered a workaround: launch the Arduino IDE, open the Serial Monitor (Ctrl-Shift-M), then close the monitor, then run `make upload`, and everything works as expected. Perhaps looking at the Arduino IDE source code to see how it initializes the port may give some clues to modifying ard-reset-arduino.

There is still one minor problem, though. There is a known issue with Cygwin make, in that the -C option to change directories can take several seconds to complete. Normally this is not an issue (other than being annoying), but in this case it causes a significant delay between the ard-reset-arduino command and the avrdude command. Because of the delay, the Arduino completes its reset and is completely up and running before avrdude is invoked. Is the reset command even necessary? My understanding of the ISP process is that the first thing the programmer does is reset the microcontroller anyway.
